filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log
    - /var/log/nginx/*.json
  processors:
    - add_docker_metadata: ~
    - add_locale: ~

output.elasticsearch:
  hosts: ["es01:9200"]
  username: "elastic"
  password: "pass@123"
